import { Link } from 'react-router-dom';
import LegalLayout from './LegalLayout';
import { COMPANY } from '../../components/PublicFooter';

// Plain-language explainer of the AI model behind card assistants and what happens to the data.
const H2 = ({ children }) => <h2 style={{ color: 'var(--surface-text)' }}>{children}</h2>;

const AiDataPrivacy = () => (
  <LegalLayout title="How our AI uses data" updated="29 September 2026">
    <p>
      Every Aicardly card can have an AI assistant that answers visitors' questions about the card owner. This page explains, in plain
      words, which AI we use, what it sees, what we keep and how we keep it safe. It adds to our{' '}
      <Link to="/privacy-policy">Privacy Policy</Link>.
    </p>

    <H2>1. The AI model</H2>
    <ul>
      <li>
        Replies are generated by <strong>Claude</strong>, a model made by <strong>Anthropic</strong>, which we call through Anthropic's
        business API.
      </li>
      <li>
        Under Anthropic's commercial terms, data sent through the API is <strong>not used to train</strong> Anthropic's models.
      </li>
      <li>We do not fine-tune or train any AI model on visitors' chats.</li>
    </ul>

    <H2>2. What the AI sees</H2>
    <ul>
      <li>The card owner's published card: name, work, services, portfolio, contact links and highlights.</li>
      <li>The notes, FAQs and knowledge base the owner wrote for their assistant.</li>
      <li>The current conversation only, up to the last 12 messages.</li>
    </ul>
    <p>
      It does <strong>not</strong> see the owner's dashboard, other visitors' chats, enquiries, analytics or anyone's account details.
    </p>

    <H2>3. How the assistant is tailored</H2>
    <p>
      Owners pick their profession (for example Doctor, Lawyer, Consultant). Each profession comes with its own rules, such as "never
      diagnose" for doctors or "no advice on your own case" for lawyers, plus suggested questions and a final offer like "Book a
      consultation". With consulting mode on, the assistant asks one or two questions to understand your need before suggesting a
      service. This tailoring is done with instructions, not by training the model on your data.
    </p>

    <H2>4. What we store</H2>
    <ul>
      <li>
        <strong>We do not store the text of AI chats.</strong> For each conversation we keep only: when it happened, how many messages
        were sent, whether any were blocked, whether the owner's offer was shown or clicked, and the 0–10 rating and comment if you
        chose to give one.
      </li>
      <li>If you send an enquiry through the card's form, it is delivered to the card owner, with your consent.</li>
      <li>The owner sees chat counts and ratings, not what you typed.</li>
    </ul>

    <H2>5. Consent</H2>
    <p>
      Before your first message, the chat shows a short notice and asks you to agree. The enquiry form has its own consent tick. You
      can stop at any time by closing the chat. To have an enquiry or rating deleted, write to{' '}
      <a href={`mailto:${COMPANY.privacyEmail}`}>{COMPANY.privacyEmail}</a>.
    </p>

    <H2>6. Guardrails</H2>
    <ul>
      <li>The assistant only answers about the card owner and their work.</li>
      <li>Attempts to make it ignore its rules or reveal its instructions are blocked.</li>
      <li>It asks visitors not to share Aadhaar, PAN, bank or card numbers, and refuses to take them.</li>
      <li>It never gives medical, legal or financial advice about your own situation. It points you to the professional instead.</li>
      <li>If someone mentions self-harm, it shares helpline numbers (Tele-MANAS 14416, emergency 112).</li>
      <li>Owners can add their own blocked topics. Each visitor has a message limit to prevent abuse.</li>
    </ul>

    <H2>7. AI can make mistakes</H2>
    <p>
      The assistant can be wrong. Please confirm important details, such as prices, availability or timings, directly with the card
      owner before you act on them.
    </p>

    <H2>Questions</H2>
    <p>
      Contact our Grievance Officer at <a href={`mailto:${COMPANY.privacyEmail}`}>{COMPANY.privacyEmail}</a> or{' '}
      <a href={COMPANY.phoneHref}>{COMPANY.phone}</a>.
    </p>
  </LegalLayout>
);

export default AiDataPrivacy;
